#!/usr/bin/env python3

from google.cloud import firestore
from faker import Faker
from numpy import random
COLLECTION = "tests"

db = firestore.Client()

# Create Document with autogenerated id
person = {
    'firstname': 'Tommy',
    'lastname': 'Tester',
    'personid': 9999
}
doc_ref = db.collection(COLLECTION).add(person)

# Create (or Replace) a Document, specifying ID
id='TimmyTester'
person = {
    'firstname': 'Timmy',
    'lastname': 'Tester',
    'personid': 9998
}
doc_ref = db.collection(COLLECTION).document(id).set(person)

# Create another document with id
id='NotTimmyNotTester'
person = {
    'firstname': 'NotTimmy',
    'lastname': 'NotTester',
    'personid': 9997
}
doc_ref = db.collection(COLLECTION).document(id).set(person)

# Add/Update Field, specifying Document ID
id='TimmyTester'
person = {
    'middlename': 'J'
}
doc_ref = db.collection(COLLECTION).document(id).update(person)

# Delete a Field, specifying Document ID
id='TimmyTester'
person = {
    'middlename': firestore.DELETE_FIELD
}
doc_ref = db.collection(COLLECTION).document(id).update(person)

# Print a document by id
id='TimmyTester'
doc = db.collection(COLLECTION).document(id).get()
print(f'{doc.id} => {doc.to_dict()}')

# Print all documents
docs = db.collection(COLLECTION).stream()
for doc in docs:
    print(f'{doc.id} => {doc.to_dict()}')

# Simple Queries
print("First Query:")
results = db.collection(COLLECTION).where('firstname','==','Tommy').stream()
for item in results:
    print(item.to_dict())

print("Second Query:")
results = db.collection(COLLECTION).where('lastname','==','Tester').stream()
for item in results:
    print(item.to_dict())

print("Third Query:")
results = db.collection(COLLECTION).where('firstname','in',['Timmy','Tommy']).stream()
for item in results:
    print(item.to_dict())

# Delete a Document
id='BadTester'
doc_ref = db.collection(COLLECTION).document(id).delete()

# To Delete a Small Collection (to do large collections - you may need to page results)
deleted = 0
docs = db.collection(COLLECTION).list_documents()
for doc in docs:
    doc.delete()
    deleted = deleted + 1
print("Deleted " + str(deleted))

print("Done")